#!/usr/bin/env python3
"""Stamp the bundle version from git so no version is hand-edited or committed."""
from pathlib import Path
import re
import subprocess

# Used outside a git checkout, such as a source tarball; keep near the latest tag.
FALLBACK_VERSION = "0.0.0"

root = Path(__file__).resolve().parent.parent


def git(*arguments):
    try:
        return subprocess.check_output(["git", "-C", str(root), *arguments],
                                       text=True, stderr=subprocess.DEVNULL).strip()
    except (subprocess.CalledProcessError, OSError):
        return ""


tag = git("describe", "--tags", "--abbrev=0")
# CFBundleShortVersionString takes at most three dot-separated integers, so a
# prerelease tag such as v0.2.0-beta.1 still stamps 0.2.0. The full tag names the
# release and the Homebrew cask; only the bundle is restricted.
numeric = re.match(r"v?(\d+(?:\.\d+){0,2})", tag)
marketing = numeric[1] if numeric else FALLBACK_VERSION
# CFBundleVersion must increase for every build macOS sees, or Launch Services
# keeps serving a cached copy of an earlier one. The commit count always does.
build = git("rev-list", "--count", "HEAD") or "1"

settings = (f"// Generated by scripts/configure-version.py from git. Do not edit.\n"
            f"MARKETING_VERSION = {marketing}\n"
            f"CURRENT_PROJECT_VERSION = {build}\n")
destination = root / "Version.local.xcconfig"
if not destination.exists() or destination.read_text() != settings:
    destination.write_text(settings)
print(f"Stamped version {marketing} ({build}) from git.")
